SQLALCHEMY_DATABASE_URI = 'sqlite:////app/superset_home/superset.db'
FEATURE_FLAGS = {
    "DASHBOARD_NATIVE_FILTERS": True,
    "DASHBOARD_NATIVE_FILTERS_SET": True,
    "ENABLE_EXPLORE_DRAG_AND_DROP": True,
    "DASHBOARD_CROSS_FILTERS": True,
}

